site_name: CropXR
site_description: Documentation for the CropXR project
site_author: CropXR
#site_url: https://ms-mint.readthedocs.io/

theme:
  name: material
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  #social:
  #  - icon: fontawesome/brands/github
  #    link: https://https://github.com/CropXR/cropxr-documentation
  #  - icon: fontawesome/brands/python
  #    link: https://cropxr.data.surf.nl
  copyright: Copyright &copy; 2025 CropXR
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage
    cookies:
      analytics:
        name: Google Analytics
        checked: true
#  analytics:
#    provider: google
#    property: G-XXXXXXXXXXX 

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started:
    - getting-started/index.md
    - Glossary: getting-started/glossary.md
  - Concepts:
    - concepts/index.md
    - Introduction: concepts/introduction.md
    - Defining a Study: concepts/defining-a-study.md
    - Metadata Model: concepts/metadata-model.md
    - What Data to Upload: concepts/what-data-to-upload.md
  - Guides:
    - guides/index.md
    - General Workflow: guides/stepwise-guide.md
    - Uploading Large Datasets: guides/uploading-large-datasets.md
  - Research Drive:
    - research-drive/index.md
    - Getting Access: research-drive/getting-access.md
    - Connecting:
      - Via Browser: research-drive/connecting/via-browser.md
      - Via NextCloud: research-drive/connecting/via-nextcloud.md
      - Via Rclone: research-drive/connecting/via-rclone.md
    - Uploading Data: research-drive/uploading-data.md
    - Sharing Data: research-drive/sharing-data.md
  - Policies:
    - policies/index.md
    - Data Sensitivity Levels: policies/data-sensitivity-levels.md
  - Resilience Hub:
    - resilience-hub/index.md
    - SEEK Metadata Entry:
      - resilience-hub/seek/index.md
      - Short Guide: resilience-hub/seek/short-guide.md
      - High-Level Example: resilience-hub/seek/high-level-example.md
      - Full Guide: resilience-hub/seek/full-guide.md
      - Reference: resilience-hub/seek/reference.md
